export const BaseIconService = {
  "clear sky": "https://img.icons8.com/sf-black-filled/64/sun.png",
  "few clouds": "https://img.icons8.com/sf-black-filled/64/partly-cloudy-day.png",
  "scattered clouds": "https://img.icons8.com/sf-black-filled/64/clouds.png",
  "broken clouds": "https://img.icons8.com/sf-black-filled/64/clouds.png",
  "overcast clouds": "https://img.icons8.com/sf-black-filled/64/partly-cloudy-day.png",
  "mist": "",
  "smoke": "",
  "haze": "https://img.icons8.com/sf-black-filled/64/fog-day.png",
  "fog": "https://img.icons8.com/sf-black-filled/64/fog-night.png",
  "dust": "",
  "sand": "",
  "squall": "",
  "tornado": "https://img.icons8.com/sf-black-filled/64/tornado.png",
  "light rain": "https://img.icons8.com/sf-black-filled/64/partly-cloudy-rain.png",
  "moderate rain": "https://img.icons8.com/sf-black-filled/64/rainy-weather.png",
  "heavy intensity rain": "https://img.icons8.com/sf-black-filled/64/rain.png",
  "very heavy rain": "https://img.icons8.com/sf-black-filled/64/rain.png",
  "extreme rain": "https://img.icons8.com/sf-black-filled/64/rain.png",
  "freezing rain": "",
  "light snow": "https://img.icons8.com/sf-black-filled/64/snow.png",
  "snow": "https://img.icons8.com/sf-black-filled/64/snow.png",
  "heavy snow": "https://img.icons8.com/sf-black-filled/64/snow-storm.png",
  "sleet": "",
  "shower sleet": "",
  "light rain and snow": "",
  "rain and snow": "",
  "light shower snow": "",
  "shower snow": "https://img.icons8.com/sf-black-filled/64/snow-storm.png",
  "heavy shower snow": "https://img.icons8.com/sf-black-filled/64/snow-storm.png",
  "thunderstorm with light rain": "https://img.icons8.com/sf-black-filled/64/chance-of-storm.png",
  "thunderstorm with rain": "https://img.icons8.com/sf-black-filled/64/storm.png",
  "thunderstorm with heavy rain": "https://img.icons8.com/sf-black-filled/64/storm.png",
  "light thunderstorm": "https://img.icons8.com/sf-black-filled/64/chance-of-storm.png",
  "thunderstorm": "https://img.icons8.com/sf-black-filled/64/cloud-lighting.png",
  "heavy thunderstorm": "https://img.icons8.com/sf-black-filled/64/cloud-lighting.png",
  "ragged thunderstorm": "https://img.icons8.com/sf-black-filled/64/cloud-lighting.png",
  "thunderstorm with light drizzle": "https://img.icons8.com/sf-black-filled/64/chance-of-storm.png",
  "thunderstorm with drizzle": "https://img.icons8.com/sf-black-filled/64/chance-of-storm.png",
  "thunderstorm with heavy drizzle": "https://img.icons8.com/sf-black-filled/64/storm.png",
}
